apiVersion: v1
kind: Service
metadata:
  name: k8s-jenkins-service
  labels:
    app: k8s-jenkins
spec:
  type: LoadBalancer
  selector:
    app: k8s-jenkins
  ports:
    - port: 8080
      name: http
      protocol: TCP
    - port: 50000
      name: agent
      protocol: TCP
